- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - tmux
        - docker
        - docker-compose
        - vim
        - keepassxc
        - terminator
        - neofetch
        - gparted
        - ufw
        - nmap
        - wireshark
        - whois
        - deluge
        - evince
